services:
  web:
    build: .
    container_name: PocketPlanner-web
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - EXCHANGERATE_API_KEY=${EXCHANGERATE_API_KEY}
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:15
    container_name: PocketPlanner-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: