# Generated by Django 5.1.5 on 2025-02-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'permissions': [('can_update_rates', 'Can update currency rates')]},
        ),
    ]
